name: dental_app
description: "My Rose Dental - Advanced AI-Powered Dental Application for Dr. Malek"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_generative_ai: ^0.4.6
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
