import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'services/dental_ai_service.dart';
import 'services/web_services.dart';

void main() { WidgetsFlutterBinding.ensureInitialized(); runApp(const App()); }
class App extends StatelessWidget { const App({super.key}); @override Widget build(BuildContext context) => MaterialApp(title:'DR MALEK ALROMIMAH DENTAL',debugShowCheckedModeBanner:false,locale:const Locale('ar','YE'),supportedLocales:const [Locale('ar','YE'),Locale('en','US')],localizationsDelegates:const [GlobalMaterialLocalizations.delegate,GlobalWidgetsLocalizations.delegate,GlobalCupertinoLocalizations.delegate],theme:ThemeData(useMaterial3:true,brightness:Brightness.dark,scaffoldBackgroundColor:C.bg,colorScheme:ColorScheme.fromSeed(seedColor:C.purple,brightness:Brightness.dark)),home:const Shell()); }
class C { static const bg=Color(0xFF170A28),panel=Color(0xFF2A123F),purple=Color(0xFFB45CFF),pink=Color(0xFFFF4FA3),text=Color(0xFFF8F0FF); }
class Shell extends StatefulWidget { const Shell({super.key}); @override State<Shell> createState()=>_ShellState(); }
class _ShellState extends State<Shell> { int tab=0; final search=TextEditingController(); final web=WebServices(); final ai=DentalAiService(); DateTime? utc; List<NewsItem> news=[]; bool loadingNews=true,loadingAi=false;
 @override void initState(){super.initState();sync();loadNews();} @override void dispose(){search.dispose();super.dispose();}
 Future<void> sync()async{final t=await web.fetchGoogleUtc();if(mounted)setState(()=>utc=t);} Future<void> loadNews()async{setState(()=>loadingNews=true);final n=await web.fetchDentalNews();if(mounted)setState((){news=n;loadingNews=false;});} Future<void> google()async{if(search.text.trim().isNotEmpty)await web.openGoogleSearch(search.text.trim());}
 Future<void> ask(String q)async{if(q.trim().isEmpty)return;setState(()=>loadingAi=true);final a=await ai.askDentalQuestion(q);if(!mounted)return;setState(()=>loadingAi=false);showDialog(context:context,builder:(_)=>AlertDialog(backgroundColor:C.panel,title:const Text('Gemini AI'),content:SingleChildScrollView(child:Text(a??'لا توجد إجابة',textDirection:TextDirection.rtl,style:const TextStyle(height:1.6))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('إغلاق'))]));}
 @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:SafeArea(child:IndexedStack(index:tab,children:[home(),library(),aiPage(),newsPage(),scholarships()])),bottomNavigationBar:nav()));
 Widget header()=>Container(padding:const EdgeInsets.all(12),decoration:glass(),child:Row(children:[bubble(Icons.medical_services),const SizedBox(width:8),const Expanded(child:Column(children:[Text('منظومة الدكتور مالك الرميمه لطب الأسنان',textAlign:TextAlign.center,style:TextStyle(fontSize:16,fontWeight:FontWeight.w900)),Text('DR MALEK ALROMIMAH DENTAL',style:TextStyle(fontSize:13,fontWeight:FontWeight.w800))])),bubble(Icons.health_and_safety)]));
 Widget searchBox()=>TextField(controller:search,onSubmitted:(_)=>google(),decoration:InputDecoration(hintText:'ابحث في جوجل',prefixIcon:IconButton(onPressed:google,icon:const Icon(Icons.search)),suffixIcon:const Icon(Icons.g_mobiledata,size:34),filled:true,fillColor:const Color(0xFF321A4C),border:OutlineInputBorder(borderRadius:BorderRadius.circular(30),borderSide:BorderSide(color:C.purple.withValues(alpha:.6)))));
 Widget home()=>RefreshIndicator(onRefresh:()async{await sync();await loadNews();},child:ListView(padding:const EdgeInsets.all(14),children:[header(),const SizedBox(height:12),searchBox(),const SizedBox(height:14),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(borderRadius:BorderRadius.circular(30),gradient:const LinearGradient(colors:[Color(0xFF4A2265),Color(0xFF21102F)]),border:Border.all(color:C.purple),boxShadow:const [BoxShadow(color:Color(0x557F35A8),blurRadius:24)]),child:Column(children:[const Text('مرحباً بك، دكتور مالك',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900)),const SizedBox(height:7),const Text('مساعدك الذكي جاهز لأي استشارة طبية وسريرية',style:TextStyle(color:Colors.white70,fontWeight:FontWeight.w700)),const SizedBox(height:18),FilledButton.icon(onPressed:()=>setState(()=>tab=2),icon:const Icon(Icons.auto_awesome),label:const Text('بدء استشارة سريرية مع Gemini AI'))])),const SizedBox(height:12),timeCard(),const SizedBox(height:16),Row(children:[feature('المنح\nالدراسية',Icons.school,4),feature('آخر الأخبار',Icons.folder,3),feature('الاستشارة\nالذكية',Icons.health_and_safety,2),feature('المكتبة\nالرقمية',Icons.menu_book,1)]),const SizedBox(height:18),Row(children:[const Expanded(child:Text('أحدث المستندات والفيديوهات',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900))),TextButton(onPressed:()=>setState(()=>tab=3),child:Text('عرض الكل'))]),if(loadingNews)const Center(child:CircularProgressIndicator()) else ...news.take(3).map(newsTile)]));
 Widget timeCard(){final t=(utc??DateTime.now().toUtc()).add(const Duration(hours:3));String z(int n)=>n.toString().padLeft(2,'0');return Container(padding:const EdgeInsets.all(15),decoration:glass(),child:Row(children:[bubble(Icons.schedule),const SizedBox(width:10),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('الوقت العالمي المتزامن',style:TextStyle(fontWeight:FontWeight.w900)),Text('مصدر الوقت: Google • UTC+03 اليمن',style:TextStyle(color:Colors.white60,fontSize:11))])),Text('${z(t.hour)}:${z(t.minute)}:${z(t.second)}',style:const TextStyle(color:C.pink,fontSize:23,fontWeight:FontWeight.w900))]));}
 Widget feature(String title,IconData icon,int to)=>Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:InkWell(onTap:()=>setState(()=>tab=to),borderRadius:BorderRadius.circular(22),child:Container(height:125,decoration:glass(22),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:42),const SizedBox(height:7),Text(title,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:12))])))));
 Widget newsTile(NewsItem n)=>Card(color:C.panel,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)),child:ListTile(onTap:()=>web.openUrl(n.link),leading:const Icon(Icons.article,color:C.pink),title:Text(n.title,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${n.source} • ${n.date}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white60)),trailing:const Icon(Icons.open_in_new,color:C.purple)));
 Widget library()=>SimplePage(title:'المكتبة الرقمية العالمية',subtitle:'بحث مباشر في PubMed، مع وصول سريع إلى Google Scholar وWHO وFDI.',body:const LibraryBody()); Widget aiPage()=>AiBody(ai:ai,loading:loadingAi,onAsk:ask); Widget newsPage()=>SimplePage(title:'آخر أخبار طب الأسنان',subtitle:'أخبار حية من Google News RSS مع فتح المصدر الأصلي.',body:NewsBody(web:web,items:news,loading:loadingNews,onRefresh:loadNews)); Widget scholarships()=>ScholarBody(web:web);
 Widget nav()=>NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),backgroundColor:const Color(0xFF1E0D2E),indicatorColor:const Color(0xFF653A85),destinations:const [NavigationDestination(icon:Icon(Icons.home),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.menu_book),label:'المكتبة'),NavigationDestination(icon:Icon(Icons.auto_awesome),label:'Gemini AI'),NavigationDestination(icon:Icon(Icons.newspaper),label:'الأخبار'),NavigationDestination(icon:Icon(Icons.school),label:'المنح')]);
 Widget bubble(IconData i)=>Container(width:42,height:42,decoration:const BoxDecoration(shape:BoxShape.circle,gradient:LinearGradient(colors:[C.purple,C.pink])),child:Icon(i)); BoxDecoration glass([double r=25])=>BoxDecoration(borderRadius:BorderRadius.circular(r),gradient:const LinearGradient(colors:[Color(0xFF35184F),Color(0xFF21102F)]),border:Border.all(color:Color(0x889B4DCE)));
}
class SimplePage extends StatelessWidget{final String title,subtitle;final Widget body;const SimplePage({super.key,required this.title,required this.subtitle,required this.body});@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Text(title,style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(subtitle,style:const TextStyle(color:Colors.white70)),const SizedBox(height:14),body]);}
class LibraryBody extends StatefulWidget{const LibraryBody({super.key});@override State<LibraryBody> createState()=>_LibraryBodyState();}
class _LibraryBodyState extends State<LibraryBody>{final q=TextEditingController(text:'dentistry');final web=WebServices();List<LibraryItem> items=[];bool loading=false;@override void initState(){super.initState();run();}Future<void> run()async{setState(()=>loading=true);final x=await web.searchPubMed(q.text);if(mounted)setState((){items=x;loading=false;});}@override void dispose(){q.dispose();super.dispose();}@override Widget build(BuildContext context)=>Column(children:[TextField(controller:q,onSubmitted:(_)=>run(),decoration:InputDecoration(hintText:'ابحث عن موضوع في طب الأسنان',suffixIcon:IconButton(onPressed:run,icon:const Icon(Icons.search)),filled:true,fillColor:C.panel,border:OutlineInputBorder(borderRadius:BorderRadius.circular(20)))),const SizedBox(height:10),Wrap(spacing:6,children:[link('PubMed','https://pubmed.ncbi.nlm.nih.gov/?term=dentistry'),link('Google Scholar','https://scholar.google.com/scholar?q=dentistry'),link('WHO Oral Health','https://www.who.int/health-topics/oral-health'),link('FDI','https://www.fdiworlddental.org/')]),const SizedBox(height:12),if(loading)const CircularProgressIndicator() else ...items.map((e)=>Card(color:C.panel,child:ListTile(onTap:()=>web.openUrl(e.link),title:Text(e.title,maxLines:2,overflow:TextOverflow.ellipsis),subtitle:Text(e.journal,style:const TextStyle(color:Colors.white60)),trailing:const Icon(Icons.open_in_new,color:C.pink))))]);Widget link(String s,String u)=>ActionChip(label:Text(s),onPressed:()=>web.openUrl(u));}
class AiBody extends StatefulWidget{final DentalAiService ai;final bool loading;final Future<void> Function(String) onAsk;const AiBody({super.key,required this.ai,required this.loading,required this.onAsk});@override State<AiBody> createState()=>_AiBodyState();}
class _AiBodyState extends State<AiBody>{final c=TextEditingController();@override void dispose(){c.dispose();super.dispose();}@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Gemini AI',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('اتصال حقيقي إلى Gemini API باستخدام مفتاح GEMINI_API_KEY في GitHub Secrets.',style:TextStyle(color:Colors.white70)),const SizedBox(height:14),Wrap(spacing:6,children:['زراعة الأسنان الفورية','ألم العصب الحاد','خطة علاج اللثة','تجميل الأسنان'].map((s)=>ActionChip(label:Text(s),onPressed:(){c.text=s;setState((){});})).toList()),const SizedBox(height:12),TextField(controller:c,minLines:4,maxLines:8,decoration:InputDecoration(hintText:'اكتب سؤالك كما في Gemini...',filled:true,fillColor:C.panel,border:OutlineInputBorder(borderRadius:BorderRadius.circular(20)))),const SizedBox(height:12),FilledButton.icon(onPressed:widget.loading?null:()=>widget.onAsk(c.text),icon:const Icon(Icons.auto_awesome),label:Text(widget.loading?'جاري الاتصال...':'اسأل Gemini الآن')),const SizedBox(height:10),const Text('للاستخدام الطبي: راجع المراجع الرسمية والبروتوكولات المحلية قبل اتخاذ قرار علاجي.',style:TextStyle(color:Colors.white54,fontSize:12))]);}
class NewsBody extends StatelessWidget{final WebServices web;final List<NewsItem> items;final bool loading;final Future<void> Function() onRefresh;const NewsBody({super.key,required this.web,required this.items,required this.loading,required this.onRefresh});@override Widget build(BuildContext context)=>Column(children:[Align(alignment:Alignment.centerLeft,child:IconButton(onPressed:onRefresh,icon:const Icon(Icons.refresh))),if(loading)const CircularProgressIndicator() else ...items.map((n)=>Card(color:C.panel,child:ListTile(onTap:()=>web.openUrl(n.link),leading:const Icon(Icons.article,color:C.pink),title:Text(n.title,maxLines:2,overflow:TextOverflow.ellipsis),subtitle:Text('${n.source} • ${n.date}',style:const TextStyle(color:Colors.white60)),trailing:const Icon(Icons.open_in_new,color:C.purple)))),FilledButton.icon(onPressed:()=>web.openGoogleSearch('طب الأسنان اليمن اخبار'),icon:const Icon(Icons.travel_explore),label:const Text('أخبار طب الأسنان في اليمن على Google'))]);}
class ScholarBody extends StatelessWidget{final WebServices web;const ScholarBody({super.key,required this.web});@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('المنح الدراسية',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('بحث حي في الويب عن منح مجانية وممولة في طب الأسنان والإدارة والتسويق ونظم المعلومات.',style:TextStyle(color:Colors.white70)),const SizedBox(height:12),...['dentistry fully funded scholarships 2026','business administration fully funded scholarships 2026','marketing fully funded scholarships 2026','information systems fully funded scholarships 2026'].map((q)=>Card(color:C.panel,child:ListTile(title:Text(q),trailing:IconButton(onPressed:()=>web.openGoogleSearch(q),icon:const Icon(Icons.search,color:C.pink))))),const SizedBox(height:10),const Text('بوابات موثوقة',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Wrap(spacing:6,children:[p('Erasmus Mundus','https://erasmus-plus.ec.europa.eu/'),p('DAAD','https://www.daad.de/en/'),p('Chevening','https://www.chevening.org/'),p('Fulbright','https://foreign.fulbrightonline.org/'),p('Study in Saudi','https://studyinsaudi.moe.gov.sa/')])]);Widget p(String s,String u)=>ActionChip(label:Text(s),onPressed:()=>web.openUrl(u));}
